home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path("", views.home, name='home'),
]

project_management/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('account/', include('users.urls')),
    path('project/', include('project.urls')),
    path('projects/', include('projects.urls')),
    path('project/<int:project_pk>/sprints/', include('sprints.urls')),
    path('project/<int:project_pk>/tasks/', include('tasks.urls')),
]

projects/urls.py
from django.urls import path

from . import views

app_name = 'projects'

urlpatterns =[
    path("", views.Projects.as_view(), name="overview"),
    path("create/", views.Create.as_view(), name="create"),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('create/', views.user_create, name='create'),
    path('', views.view_myself, name="view_myself"),
    path('account/change/', views.change, name="change"),
    # path('account/change/password/', views.change_password, name="change_password"),
    path('login/', views.user_login, name="login"),
    path('logout/', views.user_logout, name="logout"),
    path('delete/', views.account_delete, name="delete"),
]

home/views.py
from django.shortcuts import render, redirect


def home(request):
    # if user is logged in, then homepage is page with all projects
    # if user is not logged in, then homepage is login page
    if request.user.is_authenticated:
        return redirect("projects:overview")
    else:
        return redirect("users:login")

home/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <title>Zen{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}" />
    <meta charset="UTF-8">

    {# Link to bootstrap #}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>

<body class="container">
    {# Header #}
    <header class="navbar navbar-expand navbar-dark bg-dark">
        {% if user.is_authenticated %}
            {# Left sife of navbar #}
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item active">
                    <a class="navbar-brand" href="#">Zen Projects</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:change' %}">
                        <svg class="bi bi-person-fill" width="32" height="32" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3zm5-6a3 3 0 100-6 3 3 0 000 6z" clip-rule="evenodd"/></svg>
                        Account
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'projects:overview' %}">
                        <svg class="bi bi-briefcase" width="32" height="32" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M0 12.5A1.5 1.5 0 001.5 14h13a1.5 1.5 0 001.5-1.5v-6h-1v6a.5.5 0 01-.5.5h-13a.5.5 0 01-.5-.5v-6H0v6z" clip-rule="evenodd"/>
                            <path fill-rule="evenodd" d="M0 4.5A1.5 1.5 0 011.5 3h13A1.5 1.5 0 0116 4.5v2.384l-7.614 2.03a1.5 1.5 0 01-.772 0L0 6.884V4.5zM1.5 4a.5.5 0 00-.5.5v1.616l6.871 1.832a.5.5 0 00.258 0L15 6.116V4.5a.5.5 0 00-.5-.5h-13zM5 2.5A1.5 1.5 0 016.5 1h3A1.5 1.5 0 0111 2.5V3h-1v-.5a.5.5 0 00-.5-.5h-3a.5.5 0 00-.5.5V3H5v-.5z" clip-rule="evenodd"/>
                        </svg>
                        Projects
                    </a>
                </li>
            </ul>

            {# Right sife of navbar #}
            <button type="button" class="btn btn-light disabled">{{ user.username }}</button>
            <form class="form-inline my-2 my-lg-0" action="{% url 'users:logout' %}" method="POST">
                {% csrf_token %}
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Log Out</button>
            </form>
        {% else %}
            {# Left sife of navbar #}
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item active">
                    <a class="navbar-brand" href="#">Zen Projects</a>
                </li>
            </ul>
            {# Right sife of navbar #}
            <form class="form-inline my-2 my-lg-0" action="{% url 'users:create' %}" method="GET">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Sign Up</button>
            </form>
            <form class="form-inline my-2 my-lg-0" action="{% url 'home:home' %}" method="GET">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Log In</button>
            </form>
        {% endif %}
    </header>

    {# Section #}
    <section class="row top_to_bottom">
        {% block content %}
        {% endblock %}
    </section>

    {# Footer #}
    <footer class="page-footer font-small bg-light container">
          <div class="footer-copyright text-center">
              © 2020 Copyright:<br>
              <a href="https://github.com/mihsim" class="text-decoration-none text-reset">mihsim</a>
              &&
              <a href="https://github.com/he777" class="text-decoration-none text-reset">he777</a>
        </div>
    </footer>
   </body>
</html>