home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path("", views.home, name='home'),
]

project/urls.py
from django.urls import path
from . import views

app_name = 'project'

urlpatterns = [
    path("<int:project_id>/", views.ProjectView.as_view(), name="project"),
    path("<int:project_id>/delete/", views.ProjectView.delete, name="delete"),
    path("<int:project_id>/participants/", views.ProjectView.participants, name="participants"),

    path("<int:project_id>/change/", views.ProjectChangeView.as_view(), name="change"),

    path("<int:project_id>/search/participants/", views.CreateInviteToProject.as_view(), name="search_participants"),
    path("<int:project_id>/<int:participant_id>/invite/", views.CreateInviteToProject.as_view(), name="send_invite"),

    path("<int:invitation_id>/invitation/<str:action>", views.ManageInvite.as_view(), name="invitation"),

    path("<int:participation_id>/<int:user_id>/<str:action>/", views.ManageParticipation.as_view(), name="manage_participation")
]

projects/urls.py
from django.urls import path

from . import views

app_name = 'projects'

urlpatterns =[
    path("", views.Projects.as_view(), name="overview"),
    path("create/", views.Create.as_view(), name="create"),
]

sprints/urls.py
from django.urls import path

from . import views


app_name = 'sprints'
urlpatterns = [
    path("", views.all_sprints, name="all"),
    path("create/", views.create, name="create"),
    path("<int:sprint_pk>/", views.sprint_view, name="sprint"),
    path("<int:sprint_pk>/<int:task_pk>/increase/", views.increase_task_progress, name="increase_task_progress"),
    path("<int:sprint_pk>/<int:task_pk>/decrease/", views.decrease_task_progress, name="decrease_task_progress"),
]

tasks/urls.py
from django.urls import path

from . import views


app_name = "tasks"
urlpatterns = [
    path("", views.tasks_all, name="all"),
    path("create/", views.create_view, name="create"),
    path("change/<int:task_pk>/", views.change_view, name="change"),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('create/', views.user_create, name='create'),
    path('', views.view_myself, name="view_myself"),
    path('account/change/', views.change, name="change"),
    # path('account/change/password/', views.change_password, name="change_password"),
    path('login/', views.user_login, name="login"),
    path('logout/', views.user_logout, name="logout"),
    path('delete/', views.account_delete, name="delete"),
]

projects/models.py
from django.db import models

# Create your models here.

sprints/models.py
from django.db import models

from project.models import Project


class Sprint(models.Model):
    name = models.CharField(max_length=100)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    date_from = models.DateField()
    date_to = models.DateField()
    planned_story_points = models.IntegerField(default=0)

    def __str__(self):
        return self.name

project/views.py
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.views import View
from typing import List, Dict

from .models import Project, ProjectParticipants, ProjectParticipantsInvites


class ProjectView(View):
    def get(self, request, project_id):
        project = Project.objects.get(id=project_id)
        context = {"project": project}
        return render(request, "project/project.html", context)

    @classmethod
    def participants(cls, request, project_id):
        project = Project.objects.get(id=project_id)
        context = {"project": project}
        project_participants = cls.get_project_participants(project_id)
        project_invitees = cls.get_invited_to_participate(request, project_id)
        context.update(**project_participants, **project_invitees)
        return render(request, "project/participants.html", context)

    @staticmethod
    def get_project_participants(project_id: int) -> Dict[str, List]:
        try:
            participation = ProjectParticipants.objects.get(project=project_id)
        except ProjectParticipants.DoesNotExist:
            participation = None
        return {"participation": participation}

    @staticmethod
    def get_invited_to_participate(request, project_id: int) -> Dict[str, List]:
        try:
            invites = ProjectParticipantsInvites.objects.filter(project=project_id, from_user=request.user.pk)
        except ProjectParticipantsInvites.DoesNotExist:
            invites = None
        return {"invites_to_participate_in_project": invites}

    @staticmethod
    def delete(request, project_id):
        project = get_object_or_404(Project, pk=project_id)
        if request.method == "POST" and request.user == project.administrator:
            project.delete()
            return redirect('projects:overview')
        elif request.method == "GET":
            context = {'project': project,
                       'warning_message': 'Deleted project can not be restored!'}
            return render(request, 'project/delete.html', context)
        else:
            # If request.method was 'POST' but user was not administrator for project:
            return redirect('home:home')


class ProjectChangeView(View):
    def get(self, request, project_id):
        project = Project.objects.get(pk=project_id)
        context = {"project": project}
        return render(request, "project/change.html", context)

    def post(self, request, project_id):
        project = Project.objects.filter(id=project_id).first()
        project.name = request.POST["project_name"]
        project.description = request.POST["project_description"]
        project.save()
        return redirect("project:project", project_id)


class CreateInviteToProject(View):
    @staticmethod
    def get(request, project_id):
        email = request.GET.get('email_to_check')
        project = Project.objects.get(id=project_id)
        if not email:
            return render(request, "project/search_participants.html", {'project': project})
        else:
            # Check if user already is participating or is invited.
            invite_result, invite_message, contributor_found = ProjectParticipantsInvites.check_participant(project_id=project_id,
                                                                                         to_user_email=email)
            # Gives ERROR alert that user can not be added.
            if invite_result == "Error":
                return render(request, "project/search_participants.html", {'project': project,
                                                                            'invite_result': invite_result,
                                                                            'invite_message': invite_message})
            # Is returned if user with current email could be added as contributor.
            return render(request, "project/search_participants.html", {'project': project,
                                                                        'contributor_found': contributor_found})

    @staticmethod
    def post(request, project_id, participant_id):
        invite_result, invite_message = ProjectParticipantsInvites.add_invite(project_id=project_id,
                                                                              from_user_id=request.user.id,
                                                                              to_user_id=participant_id)
        project = Project.objects.get(id=project_id)
        context = {'project': project,
                   "invite_result": invite_result,
                   "invite_message": invite_message}
        if invite_result == "Successful":
            return render(request, "project/project.html", context)
        else:
            request.method = "GET"
            return render(request, "project/search_participants.html", context)


class ManageInvite(View):
    def post(self, request, invitation_id, action):
        """
        :type request: HttpRequest
        :type invitation_id: int
        :type action: str - accept, decline, delete
        :rtype: HttpResponse
        """

        invitation = get_object_or_404(ProjectParticipantsInvites, pk=invitation_id)
        # Invitee can accept and decline invite
        # Invitor can delete invite
        if action == 'accept' and invitation.to_user.id == request.user.id:
            try:
                project_participants = ProjectParticipants.objects.get(project=invitation.project)
                project_participants.user.add(invitation.to_user)
                invitation.delete()
            except ProjectParticipants.DoesNotExist:
                project_participants = ProjectParticipants.objects.create(project=invitation.project)
                project_participants.user.add(invitation.to_user)
                invitation.delete()
            return redirect('project:project', project_participants.project.id)

        elif action == 'decline' and invitation.to_user.id == request.user.id:
            invitation.status = 'Declined'
            invitation.save()
            return redirect('projects:overview')
        elif action == 'delete' and invitation.from_user.id == request.user.id:
            invitation.delete()
            return redirect('projects:overview')
        
        # 'HttpResponse('NO')'  is met for cases where user tries to change things he is not allowed
        # or typing 'acton' that does not exist.
        # FIXME HttpResponse('NO') is not working and returns "HTTP ERROR 405" instead.
        return HttpResponse('NO')


class ManageParticipation(View):
    @staticmethod
    def post(request, participation_id, user_id, action):
        participation = get_object_or_404(ProjectParticipants, pk=participation_id)
        user = get_object_or_404(User, pk=user_id)
        if action == "remove" and participation.project.administrator == request.user:
            participation.user.remove(user)
        return redirect('project:project', participation.project.pk)

projects/views.py
from django.shortcuts import render, redirect
from django.views import View

from users.models import MyUser
from project.models import Project, ProjectParticipants, ProjectParticipantsInvites


# Create your views here.
class Projects(View):
    """
    Projects page. (All projects)
    - Displays list of all projects user is administrator to.
    - Displays list of all projects user is contributor to.
    - Has button "Create new project" which leads to next page.
    """
    def get(self, request):
        user = MyUser.objects.get(id=request.user.pk)
        administrator_to = Project.objects.filter(administrator=user)
        participant_to = ProjectParticipants.objects.filter(user=user).exclude(project__administrator=user)
        invited_to = ProjectParticipantsInvites.objects.filter(to_user=user)
        context = {
            'administrator_to_projects': administrator_to,
            'participant_to_projects': participant_to,
            'invited_to_projects': invited_to,
        }
        return render(request, "projects/overview.html", context)


class Create(View):
    def get(self, request):
        return render(request, "projects/create.html")

    def post(self, request):
        project = Project.objects.create(name=request.POST["project_name"],
                                         description=request.POST["project_description"],
                                         administrator=MyUser.objects.get(id=request.user.pk)
                                         )
        project.save()

        # Project administrator must be added as project participant, so when creating tasks,
        # it would be possible to select project administrator as assignee.
        project_participants = ProjectParticipants.objects.create(project=project)
        project_participants.user.add(project.administrator)

        return redirect('projects:overview')

sprints/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse

from datetime import datetime

from .models import Sprint
from project.models import Project, ProjectParticipants
from tasks.models import Task
from project_management.settings import LOGIN_REDIRECT_URL


@login_required(login_url=LOGIN_REDIRECT_URL)
def all_sprints(request, project_pk):
    context = {}
    project = get_object_or_404(Project, pk=project_pk)
    sprints = Sprint.objects.filter(project=project)



    context['project'] = project
    context['sprints'] = sprints
    return render(request, "sprints/sprints.html", context)


@login_required(login_url=LOGIN_REDIRECT_URL)
def create(request, project_pk):
    project = get_object_or_404(Project, pk=project_pk)

    if project.administrator != request.user:
        # Only project administrator may create sprints.
        return redirect('home:home')

    content = {'project': project}
    sprint_number = len(Sprint.objects.filter(project=project)) + 1

    if request.method == "POST":

        # Check that request.post start_date is before than end_date.
        if request.POST["start_date"] > request.POST["end_date"]:
            content["error"] = "End date can not be before start date"
            return render(request, 'sprints/create.html', content)

        # Check that request.post start_date is after latest end_date in database.
        last_sprint_end_date = Sprint.objects.filter()
        if last_sprint_end_date:
            form_start_date = datetime.strptime(request.POST['start_date'], "%Y-%m-%d").date()
            db_last_date = last_sprint_end_date.latest('date_to').date_to
            if form_start_date <= db_last_date:
                content["error"] = "New sprint can not start before previous ones have ended. Latest end date: {}".format(db_last_date)
                return render(request, 'sprints/create.html', content)

        Sprint.objects.create(
            name="Sprint {0}".format(sprint_number),
            project=project,
            date_from=request.POST["start_date"],
            date_to=request.POST["end_date"],
            planned_story_points=0,
        )
        return redirect('sprints:all', project_pk)
    else:
        return render(request, 'sprints/create.html', content)


@login_required(login_url=LOGIN_REDIRECT_URL)
def sprint_view(request, project_pk, sprint_pk):
    project = get_object_or_404(Project, pk=project_pk)
    sprint = get_object_or_404(Sprint, pk=sprint_pk)
    tasks = Task.objects.filter(sprint=sprint)

    # Key-s are named same as CSS classes so it would possible to loop in HTML file.
    tasks_by_progress = {'backlog': [],
                         'todo': [],
                         'inprogress': [],
                         'qa': [],
                         'done': [],
                         }
    progress_options = [option for option in tasks_by_progress]

    for task in tasks:
        tasks_by_progress[task.progress.lower().replace(" ", "")].append(task)

    context = {'project': project,
               'sprint': sprint,
               'progress_options': progress_options,
               'tasks_by_progress': tasks_by_progress,
               }
    return render(request, 'sprints/sprint.html', context)


def get_current_progress_index(project_pk, sprint_pk, task_pk, request_user):
    project = get_object_or_404(Project, pk=project_pk)
    sprint = get_object_or_404(Sprint, pk=sprint_pk)
    task = get_object_or_404(Task, pk=task_pk)

    if sprint != task.sprint:
        return redirect("home:home")
    if project != sprint.project:
        return redirect("home:home")
    if request_user not in ProjectParticipants.get_project_participants(project):
        return redirect("home:home")

    progress_index = task.progress_sequence.index(task.progress)
    return project, sprint, task, progress_index


@login_required(login_url=LOGIN_REDIRECT_URL)
def increase_task_progress(request, project_pk, sprint_pk, task_pk):
    project, sprint, task, progress_index = get_current_progress_index(project_pk=project_pk,
                                                                       sprint_pk=sprint_pk,
                                                                       task_pk=task_pk,
                                                                       request_user=request.user,
                                                                       )
    if task.progress == task.progress_sequence[-1]:
        # It should not be possible to reach progress increase function if task has last progress option.
        return redirect("home:home")

    task.progress = task.progress_sequence[progress_index + 1]
    task.save()
    return redirect("sprints:sprint", project_pk, sprint_pk)


@login_required(login_url=LOGIN_REDIRECT_URL)
def decrease_task_progress(request, project_pk, sprint_pk, task_pk):
    project, sprint, task, progress_index = get_current_progress_index(project_pk=project_pk,
                                                                       sprint_pk=sprint_pk,
                                                                       task_pk=task_pk,
                                                                       request_user=request.user,
                                                                       )
    if task.progress == task.progress_sequence[0]:
        # It should not be possible to reach progress decrease function if task has first progress option.
        return redirect("home:home")

    task.progress = task.progress_sequence[progress_index - 1]
    task.save()
    return redirect("sprints:sprint", project_pk, sprint_pk)

templates/snippets/sidebar/account.html
<li class="nav-item">
    <a class="nav-link" href="{% url 'users:view_myself' %}">
        <svg class="bi bi-eye-fill" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path d="M10.5 8a2.5 2.5 0 11-5 0 2.5 2.5 0 015 0z"/>
            <path fill-rule="evenodd" d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8zm8 3.5a3.5 3.5 0 100-7 3.5 3.5 0 000 7z" clip-rule="evenodd"/>
        </svg>
        My Account
    </a>
</li>

templates/snippets/sidebar/account_delete.html
<li class="nav-item">
    <a class="nav-link" href="{% url 'users:delete' %}">
        <svg class="bi bi-trash" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path d="M5.5 5.5A.5.5 0 016 6v6a.5.5 0 01-1 0V6a.5.5 0 01.5-.5zm2.5 0a.5.5 0 01.5.5v6a.5.5 0 01-1 0V6a.5.5 0 01.5-.5zm3 .5a.5.5 0 00-1 0v6a.5.5 0 001 0V6z"/>
            <path fill-rule="evenodd" d="M14.5 3a1 1 0 01-1 1H13v9a2 2 0 01-2 2H5a2 2 0 01-2-2V4h-.5a1 1 0 01-1-1V2a1 1 0 011-1H6a1 1 0 011-1h2a1 1 0 011 1h3.5a1 1 0 011 1v1zM4.118 4L4 4.059V13a1 1 0 001 1h6a1 1 0 001-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z" clip-rule="evenodd"/>
        </svg>
        Delete Account
    </a>
</li>

templates/snippets/sidebar/account_update.html
<li class="nav-item">
    <a class="nav-link" href="{% url 'users:change' %}">
        <svg class="bi bi-gear" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M8.837 1.626c-.246-.835-1.428-.835-1.674 0l-.094.319A1.873 1.873 0 014.377 3.06l-.292-.16c-.764-.415-1.6.42-1.184 1.185l.159.292a1.873 1.873 0 01-1.115 2.692l-.319.094c-.835.246-.835 1.428 0 1.674l.319.094a1.873 1.873 0 011.115 2.693l-.16.291c-.415.764.42 1.6 1.185 1.184l.292-.159a1.873 1.873 0 012.692 1.116l.094.318c.246.835 1.428.835 1.674 0l.094-.319a1.873 1.873 0 012.693-1.115l.291.16c.764.415 1.6-.42 1.184-1.185l-.159-.291a1.873 1.873 0 011.116-2.693l.318-.094c.835-.246.835-1.428 0-1.674l-.319-.094a1.873 1.873 0 01-1.115-2.692l.16-.292c.415-.764-.42-1.6-1.185-1.184l-.291.159A1.873 1.873 0 018.93 1.945l-.094-.319zm-2.633-.283c.527-1.79 3.065-1.79 3.592 0l.094.319a.873.873 0 001.255.52l.292-.16c1.64-.892 3.434.901 2.54 2.541l-.159.292a.873.873 0 00.52 1.255l.319.094c1.79.527 1.79 3.065 0 3.592l-.319.094a.873.873 0 00-.52 1.255l.16.292c.893 1.64-.902 3.434-2.541 2.54l-.292-.159a.873.873 0 00-1.255.52l-.094.319c-.527 1.79-3.065 1.79-3.592 0l-.094-.319a.873.873 0 00-1.255-.52l-.292.16c-1.64.893-3.433-.902-2.54-2.541l.159-.292a.873.873 0 00-.52-1.255l-.319-.094c-1.79-.527-1.79-3.065 0-3.592l.319-.094a.873.873 0 00.52-1.255l-.16-.292c-.892-1.64.902-3.433 2.541-2.54l.292.159a.873.873 0 001.255-.52l.094-.319z" clip-rule="evenodd"/>
            <path fill-rule="evenodd" d="M8 5.754a2.246 2.246 0 100 4.492 2.246 2.246 0 000-4.492zM4.754 8a3.246 3.246 0 116.492 0 3.246 3.246 0 01-6.492 0z" clip-rule="evenodd"/>
        </svg>
        Update Account
    </a>
</li>

templates/snippets/sidebar/participant_invite.html
<li class="nav-item">
    <a class="nav-link" href="{% url 'project:search_participants' project.id %}" method="GET">
        <svg class="bi bi-person-plus-fill" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M1 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H1zm5-6a3 3 0 100-6 3 3 0 000 6zm7.5-3a.5.5 0 01.5.5v2a.5.5 0 01-.5.5h-2a.5.5 0 010-1H13V5.5a.5.5 0 01.5-.5z" clip-rule="evenodd"/>
            <path fill-rule="evenodd" d="M13 7.5a.5.5 0 01.5-.5h2a.5.5 0 010 1H14v1.5a.5.5 0 01-1 0v-2z" clip-rule="evenodd"/>
        </svg>
        Invite
    </a>
</li>

templates/snippets/sidebar/participants.html
<li class="nav-item">
    <a class="nav-link" href="{% url 'project:participants' project.pk %}">
        <svg class="bi bi-people-fill" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M7 14s-1 0-1-1 1-4 5-4 5 3 5 4-1 1-1 1H7zm4-6a3 3 0 100-6 3 3 0 000 6zm-5.784 6A2.238 2.238 0 015 13c0-1.355.68-2.75 1.936-3.72A6.325 6.325 0 005 9c-4 0-5 3-5 4s1 1 1 1h4.216zM4.5 8a2.5 2.5 0 100-5 2.5 2.5 0 000 5z" clip-rule="evenodd"/>
        </svg>
        Participants
    </a>
</li>

templates/snippets/sidebar/project_change.html
<li class="nav-item">
    <a class="nav-link" href="{% url 'project:change' project.id %}" method="GET">
        <svg class="bi bi-gear" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M8.837 1.626c-.246-.835-1.428-.835-1.674 0l-.094.319A1.873 1.873 0 014.377 3.06l-.292-.16c-.764-.415-1.6.42-1.184 1.185l.159.292a1.873 1.873 0 01-1.115 2.692l-.319.094c-.835.246-.835 1.428 0 1.674l.319.094a1.873 1.873 0 011.115 2.693l-.16.291c-.415.764.42 1.6 1.185 1.184l.292-.159a1.873 1.873 0 012.692 1.116l.094.318c.246.835 1.428.835 1.674 0l.094-.319a1.873 1.873 0 012.693-1.115l.291.16c.764.415 1.6-.42 1.184-1.185l-.159-.291a1.873 1.873 0 011.116-2.693l.318-.094c.835-.246.835-1.428 0-1.674l-.319-.094a1.873 1.873 0 01-1.115-2.692l.16-.292c.415-.764-.42-1.6-1.185-1.184l-.291.159A1.873 1.873 0 018.93 1.945l-.094-.319zm-2.633-.283c.527-1.79 3.065-1.79 3.592 0l.094.319a.873.873 0 001.255.52l.292-.16c1.64-.892 3.434.901 2.54 2.541l-.159.292a.873.873 0 00.52 1.255l.319.094c1.79.527 1.79 3.065 0 3.592l-.319.094a.873.873 0 00-.52 1.255l.16.292c.893 1.64-.902 3.434-2.541 2.54l-.292-.159a.873.873 0 00-1.255.52l-.094.319c-.527 1.79-3.065 1.79-3.592 0l-.094-.319a.873.873 0 00-1.255-.52l-.292.16c-1.64.893-3.433-.902-2.54-2.541l.159-.292a.873.873 0 00-.52-1.255l-.319-.094c-1.79-.527-1.79-3.065 0-3.592l.319-.094a.873.873 0 00.52-1.255l-.16-.292c-.892-1.64.902-3.433 2.541-2.54l.292.159a.873.873 0 001.255-.52l.094-.319z" clip-rule="evenodd"/>
            <path fill-rule="evenodd" d="M8 5.754a2.246 2.246 0 100 4.492 2.246 2.246 0 000-4.492zM4.754 8a3.246 3.246 0 116.492 0 3.246 3.246 0 01-6.492 0z" clip-rule="evenodd"/>
        </svg>
        Change project
    </a>
</li>

templates/snippets/sidebar/project_create.html
<ul class="nav flex-column">
    <li class="nav-item">
        <a class="nav-link" href="{% url 'projects:create' %}">
            <svg class="bi bi-plus" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M8 3.5a.5.5 0 01.5.5v4a.5.5 0 01-.5.5H4a.5.5 0 010-1h3.5V4a.5.5 0 01.5-.5z" clip-rule="evenodd"/>
                <path fill-rule="evenodd" d="M7.5 8a.5.5 0 01.5-.5h4a.5.5 0 010 1H8.5V12a.5.5 0 01-1 0V8z" clip-rule="evenodd"/>
            </svg>
            Add Project
        </a>
    </li>
</ul>

templates/snippets/sidebar/project_delete.html
<li class="nav-item">
    <a class="nav-link" href="{% url 'project:delete' project.id %}" method="GET">
        <svg class="bi bi-trash" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path d="M5.5 5.5A.5.5 0 016 6v6a.5.5 0 01-1 0V6a.5.5 0 01.5-.5zm2.5 0a.5.5 0 01.5.5v6a.5.5 0 01-1 0V6a.5.5 0 01.5-.5zm3 .5a.5.5 0 00-1 0v6a.5.5 0 001 0V6z"/>
            <path fill-rule="evenodd" d="M14.5 3a1 1 0 01-1 1H13v9a2 2 0 01-2 2H5a2 2 0 01-2-2V4h-.5a1 1 0 01-1-1V2a1 1 0 011-1H6a1 1 0 011-1h2a1 1 0 011 1h3.5a1 1 0 011 1v1zM4.118 4L4 4.059V13a1 1 0 001 1h6a1 1 0 001-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z" clip-rule="evenodd"/>
        </svg>
        Delete project
    </a>
</li>

templates/snippets/sidebar/sprint_create.html
<li class="nav-item">
    <a class="nav-link" href="{% url 'sprints:create' project.pk %}">
        <svg class="bi bi-plus" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M8 3.5a.5.5 0 01.5.5v4a.5.5 0 01-.5.5H4a.5.5 0 010-1h3.5V4a.5.5 0 01.5-.5z" clip-rule="evenodd"/>
            <path fill-rule="evenodd" d="M7.5 8a.5.5 0 01.5-.5h4a.5.5 0 010 1H8.5V12a.5.5 0 01-1 0V8z" clip-rule="evenodd"/>
        </svg>
        Add Sprint
    </a>
</li>