home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path("", views.home, name='home'),
]

project/urls.py
from django.urls import path
from . import views

app_name = 'project'

urlpatterns = [
    path("<int:project_id>/", views.ProjectView.as_view(), name="project"),
    path("<int:project_id>/delete/", views.ProjectView.delete, name="delete"),
    path("<int:project_id>/participants/", views.ProjectView.participants, name="participants"),

    path("<int:project_id>/change/", views.ProjectChangeView.as_view(), name="change"),

    path("<int:project_id>/search/participants/", views.CreateInviteToProject.as_view(), name="search_participants"),
    path("<int:project_id>/<int:participant_id>/invite/", views.CreateInviteToProject.as_view(), name="send_invite"),

    path("<int:invitation_id>/invitation/<str:action>", views.ManageInvite.as_view(), name="invitation"),

    path("<int:participation_id>/<int:user_id>/<str:action>/", views.ManageParticipation.as_view(), name="manage_participation")
]

project_management/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('account/', include('users.urls')),
    path('project/', include('project.urls')),
    path('projects/', include('projects.urls')),
    path('project/<int:project_pk>/sprints/', include('sprints.urls')),
    path('project/<int:project_pk>/tasks/', include('tasks.urls')),
]

projects/urls.py
from django.urls import path

from . import views

app_name = 'projects'

urlpatterns =[
    path("", views.Projects.as_view(), name="overview"),
    path("create/", views.Create.as_view(), name="create"),
]

project/models.py
from django.db import models

from users.models import MyUser


class Project(models.Model):
    name = models.CharField(max_length=150)
    description = models.TextField(blank=True)
    administrator = models.ForeignKey(MyUser, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class ProjectParticipants(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    user = models.ManyToManyField(MyUser)

    @classmethod
    def get_project_participants(cls, project):
        """Used to provide assignee selection in Task form."""
        try:
            project_participants = cls.objects.get(project=project)
            return project_participants.user.all()
        except cls.DoesNotExist:
            return MyUser.objects.none()

    def __str__(self):
        return self.project.name


class ProjectParticipantsInvites(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    from_user = models.ForeignKey(MyUser, on_delete=models.CASCADE, related_name="from_user")
    to_user = models.ForeignKey(MyUser, on_delete=models.CASCADE, related_name="to_user")
    status = models.CharField(max_length=10, default='Waiting')

    @classmethod
    def add_invite(cls, project_id, from_user_id, to_user_id):
        """
        This function is accessed when project administrator click invite participant button.
        1. Checks that project and users with provided id-s exist
        2. Checks that project does not have to_user as participant
        3. Checks that to_user does not have invitation to participate in project
        4. Save invite
        """

        try:  # 1
            project = Project.objects.get(id=project_id)
            from_user = MyUser.objects.get(id=from_user_id)
            to_user = MyUser.objects.get(id=to_user_id)
        except (Project.DoesNotExist, MyUser.DoesNotExist):
            return "Error", "Bad data provided!"

        try:  # 2
            ProjectParticipants.objects.get(project=project_id, user=to_user)
            return "Error", "This user is already participating!"
        except ProjectParticipants.DoesNotExist:
            pass

        try:  # 3
            invite = cls.objects.get(project=project_id, to_user=to_user_id)
            return "Error", f"This user is invited already, invite status is: {invite.status}"
        except cls.DoesNotExist:
            # 4
            invite = cls(project=project, from_user=from_user, to_user=to_user)
            invite.save()
            return "Success", "Invitation successfully sent."


    @classmethod
    def check_participant(cls, project_id, to_user_email):
        """
        Checks if user with given email address is participating to project with given ID

        :param project_id: Primary key to project
        :param to_user_email: Email address to user that will be checked
        :type project_id: int
        :type to_user_email: str
        :return: Returns message text with user instance if user exists.
        :rtype: Tuple(string, string, User instance) or Tuple(string, string, None)
        """
        try:
            to_user = MyUser.objects.get(email=to_user_email)
        except MyUser.DoesNotExist:
            return "Error", "No registered user has that email.", None
        try:
            ProjectParticipants.objects.get(project=project_id, user=to_user)
            return "Error", "This user is already participating!", to_user
        except ProjectParticipants.DoesNotExist:
            pass
        try:
            invite = cls.objects.get(project=project_id, to_user=to_user.id)
            return "Error", f"This user is invited already, invite status is: {invite.status}", to_user
        except cls.DoesNotExist:
            return "Success", "Invitation can be sent.", to_user

    def __str__(self):
        return f"Project: {self.project.name}. From: {self.from_user.username}. To: {self.to_user.username}."

projects/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render, redirect


def home(request):
    # if user is logged in, then homepage is page with all projects
    # if user is not logged in, then homepage is login page
    if request.user.is_authenticated:
        return redirect("projects:overview")
    else:
        return redirect("users:login")

project/views.py
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.views import View
from typing import List, Dict

from .models import Project, ProjectParticipants, ProjectParticipantsInvites


class ProjectView(View):
    def get(self, request, project_id):
        project = Project.objects.get(id=project_id)
        context = {"project": project}
        return render(request, "project/project.html", context)

    @classmethod
    def participants(cls, request, project_id):
        project = Project.objects.get(id=project_id)
        context = {"project": project}
        project_participants = cls.get_project_participants(project_id)
        project_invitees = cls.get_invited_to_participate(request, project_id)
        context.update(**project_participants, **project_invitees)
        return render(request, "project/participants.html", context)

    @staticmethod
    def get_project_participants(project_id: int) -> Dict[str, List]:
        try:
            participation = ProjectParticipants.objects.get(project=project_id)
        except ProjectParticipants.DoesNotExist:
            participation = None
        return {"participation": participation}

    @staticmethod
    def get_invited_to_participate(request, project_id: int) -> Dict[str, List]:
        try:
            invites = ProjectParticipantsInvites.objects.filter(project=project_id, from_user=request.user.pk)
        except ProjectParticipantsInvites.DoesNotExist:
            invites = None
        return {"invites_to_participate_in_project": invites}

    @staticmethod
    def delete(request, project_id):
        project = get_object_or_404(Project, pk=project_id)
        if request.method == "POST" and request.user == project.administrator:
            project.delete()
            return redirect('projects:overview')
        elif request.method == "GET":
            context = {'project': project,
                       'warning_message': 'Deleted project can not be restored!'}
            return render(request, 'project/delete.html', context)
        else:
            # If request.method was 'POST' but user was not administrator for project:
            return redirect('home:home')


class ProjectChangeView(View):
    def get(self, request, project_id):
        project = Project.objects.get(pk=project_id)
        context = {"project": project}
        return render(request, "project/change.html", context)

    def post(self, request, project_id):
        project = Project.objects.filter(id=project_id).first()
        project.name = request.POST["project_name"]
        project.description = request.POST["project_description"]
        project.save()
        return redirect("project:project", project_id)


class CreateInviteToProject(View):
    @staticmethod
    def get(request, project_id):
        email = request.GET.get('email_to_check')
        project = Project.objects.get(id=project_id)
        if not email:
            return render(request, "project/search_participants.html", {'project': project})
        else:
            # Check if user already is participating or is invited.
            invite_result, invite_message, contributor_found = ProjectParticipantsInvites.check_participant(project_id=project_id,
                                                                                         to_user_email=email)
            # Gives ERROR alert that user can not be added.
            if invite_result == "Error":
                return render(request, "project/search_participants.html", {'project': project,
                                                                            'invite_result': invite_result,
                                                                            'invite_message': invite_message})
            # Is returned if user with current email could be added as contributor.
            return render(request, "project/search_participants.html", {'project': project,
                                                                        'contributor_found': contributor_found})

    @staticmethod
    def post(request, project_id, participant_id):
        invite_result, invite_message = ProjectParticipantsInvites.add_invite(project_id=project_id,
                                                                              from_user_id=request.user.id,
                                                                              to_user_id=participant_id)
        project = Project.objects.get(id=project_id)
        context = {'project': project,
                   "invite_result": invite_result,
                   "invite_message": invite_message}
        if invite_result == "Successful":
            return render(request, "project/project.html", context)
        else:
            request.method = "GET"
            return render(request, "project/search_participants.html", context)


class ManageInvite(View):
    def post(self, request, invitation_id, action):
        """
        :type request: HttpRequest
        :type invitation_id: int
        :type action: str - accept, decline, delete
        :rtype: HttpResponse
        """

        invitation = get_object_or_404(ProjectParticipantsInvites, pk=invitation_id)
        # Invitee can accept and decline invite
        # Invitor can delete invite
        if action == 'accept' and invitation.to_user.id == request.user.id:
            try:
                project_participants = ProjectParticipants.objects.get(project=invitation.project)
                project_participants.user.add(invitation.to_user)
                invitation.delete()
            except ProjectParticipants.DoesNotExist:
                project_participants = ProjectParticipants.objects.create(project=invitation.project)
                project_participants.user.add(invitation.to_user)
                invitation.delete()
            return redirect('project:project', project_participants.project.id)

        elif action == 'decline' and invitation.to_user.id == request.user.id:
            invitation.status = 'Declined'
            invitation.save()
            return redirect('projects:overview')
        elif action == 'delete' and invitation.from_user.id == request.user.id:
            invitation.delete()
            return redirect('projects:overview')
        
        # 'HttpResponse('NO')'  is met for cases where user tries to change things he is not allowed
        # or typing 'acton' that does not exist.
        # FIXME HttpResponse('NO') is not working and returns "HTTP ERROR 405" instead.
        return HttpResponse('NO')


class ManageParticipation(View):
    @staticmethod
    def post(request, participation_id, user_id, action):
        participation = get_object_or_404(ProjectParticipants, pk=participation_id)
        user = get_object_or_404(User, pk=user_id)
        if action == "remove" and participation.project.administrator == request.user:
            participation.user.remove(user)
        return redirect('project:project', participation.project.pk)

projects/views.py
from django.shortcuts import render, redirect
from django.views import View

from users.models import MyUser
from project.models import Project, ProjectParticipants, ProjectParticipantsInvites


# Create your views here.
class Projects(View):
    """
    Projects page. (All projects)
    - Displays list of all projects user is administrator to.
    - Displays list of all projects user is contributor to.
    - Has button "Create new project" which leads to next page.
    """
    def get(self, request):
        user = MyUser.objects.get(id=request.user.pk)
        administrator_to = Project.objects.filter(administrator=user)
        participant_to = ProjectParticipants.objects.filter(user=user).exclude(project__administrator=user)
        invited_to = ProjectParticipantsInvites.objects.filter(to_user=user)
        context = {
            'administrator_to_projects': administrator_to,
            'participant_to_projects': participant_to,
            'invited_to_projects': invited_to,
        }
        return render(request, "projects/overview.html", context)


class Create(View):
    def get(self, request):
        return render(request, "projects/create.html")

    def post(self, request):
        project = Project.objects.create(name=request.POST["project_name"],
                                         description=request.POST["project_description"],
                                         administrator=MyUser.objects.get(id=request.user.pk)
                                         )
        project.save()

        # Project administrator must be added as project participant, so when creating tasks,
        # it would be possible to select project administrator as assignee.
        project_participants = ProjectParticipants.objects.create(project=project)
        project_participants.user.add(project.administrator)

        return redirect('projects:overview')

project/templates/project/base_with_sidebar.html
{% extends 'base.html' %}
{% block title %}|Project{% endblock %}

{% block content %}
   <!-- SIDEBAR -->
    <nav id="nav_sidebar">
        <div class="sidebar-sticky" id="sidebar">
            <ul class="nav flex-column">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'project:project' project.pk %}">
                        <svg class="bi bi-briefcase-fill" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M0 12.5A1.5 1.5 0 001.5 14h13a1.5 1.5 0 001.5-1.5V6.85L8.129 8.947a.5.5 0 01-.258 0L0 6.85v5.65z" clip-rule="evenodd"/>
                            <path fill-rule="evenodd" d="M0 4.5A1.5 1.5 0 011.5 3h13A1.5 1.5 0 0116 4.5v1.384l-7.614 2.03a1.5 1.5 0 01-.772 0L0 5.884V4.5zm5-2A1.5 1.5 0 016.5 1h3A1.5 1.5 0 0111 2.5V3h-1v-.5a.5.5 0 00-.5-.5h-3a.5.5 0 00-.5.5V3H5v-.5z" clip-rule="evenodd"/>
                        </svg>
                        {{ project.name|truncatechars:15 }}
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">
                        <svg class="bi bi-stopwatch" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M8 15A6 6 0 108 3a6 6 0 000 12zm0 1A7 7 0 108 2a7 7 0 000 14z" clip-rule="evenodd"/>
                            <path fill-rule="evenodd" d="M8 4.5a.5.5 0 01.5.5v4a.5.5 0 01-.5.5H4.5a.5.5 0 010-1h3V5a.5.5 0 01.5-.5zM5.5.5A.5.5 0 016 0h4a.5.5 0 010 1H6a.5.5 0 01-.5-.5z" clip-rule="evenodd"/>
                            <path d="M7 1h2v2H7V1z"/>
                        </svg>
                        Sprints<div style="background-color: red">Missing</div>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">
                        <svg class="bi bi-list-task" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M2 2.5a.5.5 0 00-.5.5v1a.5.5 0 00.5.5h1a.5.5 0 00.5-.5V3a.5.5 0 00-.5-.5H2zM3 3H2v1h1V3z" clip-rule="evenodd"/>
                            <path d="M5 3.5a.5.5 0 01.5-.5h9a.5.5 0 010 1h-9a.5.5 0 01-.5-.5zM5.5 7a.5.5 0 000 1h9a.5.5 0 000-1h-9zm0 4a.5.5 0 000 1h9a.5.5 0 000-1h-9z"/>
                            <path fill-rule="evenodd" d="M1.5 7a.5.5 0 01.5-.5h1a.5.5 0 01.5.5v1a.5.5 0 01-.5.5H2a.5.5 0 01-.5-.5V7zM2 7h1v1H2V7zm0 3.5a.5.5 0 00-.5.5v1a.5.5 0 00.5.5h1a.5.5 0 00.5-.5v-1a.5.5 0 00-.5-.5H2zm1 .5H2v1h1v-1z" clip-rule="evenodd"/>
                        </svg>
                        Tasks<div style="background-color: red">Missing</div>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'project:participants' project.pk %}">
                        <svg class="bi bi-people-fill" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M7 14s-1 0-1-1 1-4 5-4 5 3 5 4-1 1-1 1H7zm4-6a3 3 0 100-6 3 3 0 000 6zm-5.784 6A2.238 2.238 0 015 13c0-1.355.68-2.75 1.936-3.72A6.325 6.325 0 005 9c-4 0-5 3-5 4s1 1 1 1h4.216zM4.5 8a2.5 2.5 0 100-5 2.5 2.5 0 000 5z" clip-rule="evenodd"/>
                        </svg>
                        Participants
                    </a>
                </li>
                {# Buttons to 'change' and 'delete' project #}
                {# Visible only to project administrator #}
                {% if project.administrator == user %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'project:search_participants' project.id %}" method="GET">
                            <svg class="bi bi-person-plus-fill" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd" d="M1 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H1zm5-6a3 3 0 100-6 3 3 0 000 6zm7.5-3a.5.5 0 01.5.5v2a.5.5 0 01-.5.5h-2a.5.5 0 010-1H13V5.5a.5.5 0 01.5-.5z" clip-rule="evenodd"/>
                                <path fill-rule="evenodd" d="M13 7.5a.5.5 0 01.5-.5h2a.5.5 0 010 1H14v1.5a.5.5 0 01-1 0v-2z" clip-rule="evenodd"/>
                            </svg>
                            Invite
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'project:change' project.id %}" method="GET">
                            <svg class="bi bi-gear" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd" d="M8.837 1.626c-.246-.835-1.428-.835-1.674 0l-.094.319A1.873 1.873 0 014.377 3.06l-.292-.16c-.764-.415-1.6.42-1.184 1.185l.159.292a1.873 1.873 0 01-1.115 2.692l-.319.094c-.835.246-.835 1.428 0 1.674l.319.094a1.873 1.873 0 011.115 2.693l-.16.291c-.415.764.42 1.6 1.185 1.184l.292-.159a1.873 1.873 0 012.692 1.116l.094.318c.246.835 1.428.835 1.674 0l.094-.319a1.873 1.873 0 012.693-1.115l.291.16c.764.415 1.6-.42 1.184-1.185l-.159-.291a1.873 1.873 0 011.116-2.693l.318-.094c.835-.246.835-1.428 0-1.674l-.319-.094a1.873 1.873 0 01-1.115-2.692l.16-.292c.415-.764-.42-1.6-1.185-1.184l-.291.159A1.873 1.873 0 018.93 1.945l-.094-.319zm-2.633-.283c.527-1.79 3.065-1.79 3.592 0l.094.319a.873.873 0 001.255.52l.292-.16c1.64-.892 3.434.901 2.54 2.541l-.159.292a.873.873 0 00.52 1.255l.319.094c1.79.527 1.79 3.065 0 3.592l-.319.094a.873.873 0 00-.52 1.255l.16.292c.893 1.64-.902 3.434-2.541 2.54l-.292-.159a.873.873 0 00-1.255.52l-.094.319c-.527 1.79-3.065 1.79-3.592 0l-.094-.319a.873.873 0 00-1.255-.52l-.292.16c-1.64.893-3.433-.902-2.54-2.541l.159-.292a.873.873 0 00-.52-1.255l-.319-.094c-1.79-.527-1.79-3.065 0-3.592l.319-.094a.873.873 0 00.52-1.255l-.16-.292c-.892-1.64.902-3.433 2.541-2.54l.292.159a.873.873 0 001.255-.52l.094-.319z" clip-rule="evenodd"/>
                                <path fill-rule="evenodd" d="M8 5.754a2.246 2.246 0 100 4.492 2.246 2.246 0 000-4.492zM4.754 8a3.246 3.246 0 116.492 0 3.246 3.246 0 01-6.492 0z" clip-rule="evenodd"/>
                            </svg>
                            Change
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'project:delete' project.id %}" method="GET">
                            <svg class="bi bi-trash" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                <path d="M5.5 5.5A.5.5 0 016 6v6a.5.5 0 01-1 0V6a.5.5 0 01.5-.5zm2.5 0a.5.5 0 01.5.5v6a.5.5 0 01-1 0V6a.5.5 0 01.5-.5zm3 .5a.5.5 0 00-1 0v6a.5.5 0 001 0V6z"/>
                                <path fill-rule="evenodd" d="M14.5 3a1 1 0 01-1 1H13v9a2 2 0 01-2 2H5a2 2 0 01-2-2V4h-.5a1 1 0 01-1-1V2a1 1 0 011-1H6a1 1 0 011-1h2a1 1 0 011 1h3.5a1 1 0 011 1v1zM4.118 4L4 4.059V13a1 1 0 001 1h6a1 1 0 001-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z" clip-rule="evenodd"/>
                            </svg>
                            Delete
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <!-- Section -->
    <div class="col" >
        <div class="display-4 text-center">{% block content_title %}
        {% endblock %}
        </div>
        <hr class="my-4">
        {% block content_body %}
        {% endblock %}
    </div>
{% endblock %}

project/templates/project/change.html
{% extends 'base.html' %}

{% block title %}|Change{% endblock %}

{% block sidebar %}
    {% include "project/sidebar.html" %}
{% endblock %}

{% block body_title %}
    Change project
{% endblock %}

{% block body_content %}
    <form action="{% url 'project:change' project.pk %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="exampleInputPassword1">Project name</label>
            <input type="text" class="form-control" id="exampleInputPassword1" name="project_name" value="{{ project.name }}" required>
        </div>
        <div class="form-group">
            <label for="exampleFormControlTextarea1">Project description</label>
            <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="project_description">{{ project.description }}</textarea>
        </div>
        <div class="text-center">
            <button class="btn btn-primary" type="submit">Change</button>
        </div>
    </form>
{% endblock %}

project/templates/project/delete.html
{% extends 'base.html' %}

{% block title %}|Delete project{% endblock %}

{% block sidebar %}
    {% include "project/sidebar.html" %}
{% endblock %}
{% block body_title %}
    Delete project
{% endblock %}

{% block body_content %}
    <div class="alert alert-danger" role="alert">{{ warning_message }}</div>
    <form action="{% url 'project:delete' project.pk %}" method="POST"  class="text-center">
        {% csrf_token %}
        <button type="submit" class="btn btn-outline-danger">Delete</button>
    </form>
{% endblock %}

project/templates/project/home.html
{% extends 'project/base_with_sidebar.html' %}

{% block content_title %}
    Project page
{% endblock %}

{% block content_body %}
    <a href="{% url 'project:create' %}" >
        <button class="btn btn-primary">Create new project</button>
    </a>
    <hr>

    {# Prints out list of projects user is administrator to. #}
    {% if administrator_to_projects %}
        <h3>You are administrator to:</h3>
        <ul class="list-group">
            {% for project in administrator_to_projects %}
                <a href="{% url "project:project" project.id %}" class="list-group-item list-group-item-action">{{ project }}</a>
            {% endfor %}
        </ul>
    {% endif %}


    {# Prints out list of projects user is participating, but is not administrator to. #}
    {% if participations_to_projects %}
        <h3>You are contributor to:</h3>
        <ul class="list-group">
            {% for participation in participations_to_projects %}
                {# project.project.id - project instance has a foreing key field named project.#}
                <a href="{% url "project:project" participation.project.id %}" class="list-group-item list-group-item-action">{{ participation.project.name }}</a>
            {% endfor %}
        </ul>
    {% endif %}


    {# Prints out list of projects that user is invited to. #}
    {% if invitations_to_projects %}
        <h3>You are invited to:</h3>
        {% for invitation in invitations_to_projects %}
            {% if invitation.status != "Declined"  %}
                <li class="list-group-item">
                    <form role="form"  action="{% url 'project:invitation' invitation.id 'accept' %}" method="POST" class="row">
                        {% csrf_token %}
                        <div class="col">{{ invitation.project.name }}</div>
                        <div class="col-auto">
                            <button class="btn btn-outline-secondary btn-sm" type="submit" formaction="{% url 'project:invitation' invitation.id 'decline' %}">Decline</button>
                            <button class="btn btn-outline-success btn-sm" type="submit">Accept</button>
                        </div>
                    </form>
                </li>
            {% endif %}
        {% endfor %}
    {% endif %}

{% endblock %}

project/templates/project/participants.html
{% extends 'base.html' %}
{% block title %}|Participants{% endblock %}

{% block sidebar %}
    {% include "project/sidebar.html" %}
{% endblock %}

{% block body_title %}
    Participants
{% endblock %}

{% block body_content %}
    {# If selected project has participants, then they are printed out #}
    {# Project administrator can remove paricipants #}
    <ul class="list-group">
        <h3>Project participants:</h3>
        {% if participation.user.all %}
            {% for user in participation.user.all %}
                <li class="list-group-item">
                    <form action="{% url 'project:manage_participation' participation.pk user.pk 'remove' %}" method="POST" class="row">
                        {% csrf_token %}
                        <div class="col">{{ user.username }}</div>
                        {% if participation.project.administrator == request.user %}
                        <div class="col-auto"><button type="submit" class="btn btn-outline-danger btn-sm">Remove</button></div>
                        {% endif %}
                    </form>
                </li>
            {% endfor %}
        {% else %}
            <li class="list-group-item">This project has no participants</li>
        {% endif %}
    </ul>

    {# If project has invited participants who have not accepted the inviteinvites, then they will be printed out:  #}
    {# Visible only to project administrator #}
    {% if project.administrator ==  user %}
        <ul class="list-group">
            <h3>Invited to participate:</h3>
            {% if invites_to_participate_in_project %}
                {% for invitation in invites_to_participate_in_project %}
                    <li class="list-group-item">
                        <form action="{% url 'project:invitation' invitation.id 'delete' %}" method="POST" class="row">
                            {% csrf_token %}
                            <div class="col">{{ invitation.to_user.username }}</div>
                            {% if invitation.status == 'Waiting' %}
                                <button class="btn btn-outline-warning btn.sm col-auto" disabled>{{ invitation.status }}</button>
                            {% elif invitation.status == 'Declined'%}
                                 <button class="btn btn-outline-secondary btn.sm col-auto" disabled>{{ invitation.status }}</button>
                            {% endif %}
                            <button class="btn btn-outline-danger btn-sm col-auto">Delete</button>
                        </form>
                    </li>
                {% endfor %}
            {% else %}
                <li class="list-group-item">Nobody is invited to participate.</li>
            {% endif %}
        </ul>
    {% endif %}
{% endblock %}

project/templates/project/search_participants.html
{% extends 'base.html' %}

{% block sidebar %}
    {% include "project/sidebar.html" %}
{% endblock %}

{% block body_title %}
    Search users
{% endblock %}


{% block body_content %}

    {{ email }}
    {# Search filed is always shown. #}
    {% if request.method == "GET" %}
        <h3>Search users:</h3>
        <form class="form-inline my-2 my-lg-0" action="{% url 'project:search_participants' project.id %}" method="GET">
            {% csrf_token %}
            <input class="form-control mr-sm-2" type="search" placeholder="email" aria-label="Search" name="email_to_check">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    {% endif %}

    {# Shows alert message. Should be shown only when invite was unsuccessful #}
    {% if invite_result == "Error" %}
            <div class="alert alert-danger">{{ invite_message }}</div>
        {% elif invite_result == "Success" %}
            <div class="alert alert-success">{{ invite_message }}</div>
    {% endif %}

    {# if 'POST' request had 'contributor_found' #}

    {% if contributor_found and not invite_message %}
        <form action="{% url 'project:send_invite' project.id contributor_found.id %}" method="POST">
            {% csrf_token %}
            <ul class="list-group-flush">
                <li class="list-group-item"><h3>We found:</h3></li>
                <li class="list-group-item">
                    Username: {{ contributor_found.username }}<br>
                    Email: {{ contributor_found.email }}
                </li>
            </ul>
            <div class="text-center">
                <button class="btn btn-primary">Send invite</button>
            </div>
        </form>
    {% endif %}

    {# Is shown when email was searched but it was not found in database. #}
    {% if contributor_not_found %}
        <div class="alert alert-danger" role="alert">{{ contributor_not_found }}</div>
    {% endif %}

{% endblock %}