home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path("", views.home, name='home'),
]

project_management/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('account/', include('users.urls')),
    path('project/', include('project.urls')),
    path('projects/', include('projects.urls')),
    path('project/<int:project_pk>/sprints/', include('sprints.urls')),
    path('project/<int:project_pk>/tasks/', include('tasks.urls')),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('create/', views.user_create, name='create'),
    path('', views.view_myself, name="view_myself"),
    path('account/change/', views.change, name="change"),
    # path('account/change/password/', views.change_password, name="change_password"),
    path('login/', views.user_login, name="login"),
    path('logout/', views.user_logout, name="logout"),
    path('delete/', views.account_delete, name="delete"),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager


class MyUserManager(BaseUserManager):
    def create_user(self, email, username, password=None):
        """ Takes as parameters USERNAME_FIELD & REQUIRED_FIELDS """
        if not email:
            raise ValueError("Users must have an email address.")
        if not username:
            raise ValueError("Users must have a username.")
        user = self.model(
            email=self.normalize_email(email),  # normalize_email() - changes domain name part - domain_part.lower()
            username=username,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password):
        user = self.create_user(
            email=self.normalize_email(email),
            username=username,
            password=password,
        )
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


# Custom user model
class MyUser(AbstractBaseUser):
    email = models.EmailField(verbose_name="email", max_length=60, unique=True)
    username            = models.CharField(max_length=30, unique=True)
    date_joined         = models.DateTimeField(verbose_name="date joined", auto_now_add=True)
    last_login          = models.DateTimeField(verbose_name="last login", auto_now=True)
    is_admin            = models.BooleanField(default=False)
    is_active           = models.BooleanField(default=True)
    is_staff            = models.BooleanField(default=False)
    is_superuser        = models.BooleanField(default=False)

    # USERNAME_FIELD is used to log in
    USERNAME_FIELD = "email"

    # REQUIRED_FIELDS must be filled in addition to USERNAME_FIELD to register.
    REQUIRED_FIELDS = ["username", ]

    # Telling custom user model (User) what name his manager has.
    objects = MyUserManager()

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return True

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, ReadOnlyPasswordHashField, PasswordChangeForm
from django.contrib.auth import authenticate

from .models import MyUser


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(max_length=60, help_text="Required, add valid email address.")

    class Meta:
        model = MyUser
        fields = ("email", "username", "password1", "password2")


class UserAuthenticationForm(forms.ModelForm):
    # widget=forms.PasswordInput - changes characters to ---> **************
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

    class Meta:
        model = MyUser  # Tells what fields will be available
        fields = ("email", "password", )  # Tells which fields will be shown.

    def clean(self):
        # clean method is available to every form that inherits from django.forms.ModelForm
        # claen(self) is run before form can do anything
        # so any logic writen here will be run first.
        if self.is_valid():  # False id password has a wrong format.
            email = self.cleaned_data["email"]
            password = self.cleaned_data["password"]
            if not authenticate(email=email, password=password):
                raise forms.ValidationError("Invalid login")


class MyUserChangeForm(UserChangeForm):
    password = None

    class Meta:
        model = MyUser
        fields = ("username", "email")

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from .models import MyUser
from .forms import RegistrationForm, UserAuthenticationForm, MyUserChangeForm


def user_create(request):
    context = {}
    if request.method == "POST":
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            email = form.cleaned_data.get("email")
            raw_password = form.cleaned_data.get("password1")
            user = authenticate(email=email, password=raw_password)
            login(request, user)
            return redirect("home:home")
        else:
            context["registration_form"] = form
    else:
        form = RegistrationForm()
        context["registration_form"] = form
    return render(request, "users/create.html", context)


def user_logout(request):
    logout(request)
    return redirect("home:home")


def user_login(request):
    context = {}

    user = request.user
    if user.is_authenticated:
        # If user is authenticated, then there is no need to show login screen.
        redirect("home:home")

    if request.method == "POST":
        form = UserAuthenticationForm(request.POST)
        if form.is_valid():
            email = request.POST["email"]
            password = request.POST["password"]
            user = authenticate(email=email, password=password)

            if user:
                # if user exists then it means that user was successfully authenticated.
                login(request, user)
                return redirect("home:home")

    else:
        form = UserAuthenticationForm()

    context["login_form"] = form
    return render(request, "users/login.html", context)


def view_myself(request):
    user = MyUser.objects.get(pk=request.user.pk)
    return render(request, 'users/view_myself.html', {'date_registered': user.date_joined})


def change(request):
    context = {}
    if request.method == 'POST':
        form = MyUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
        return redirect("users:view_myself")
    else:
        form = MyUserChangeForm(instance=request.user)
        context['form'] = form
        return render(request, 'users/change.html', context)


@login_required
def account_delete(request):
    if request.method == 'GET':
        warning_message = "Deleted account can not be restored! All projects created by you will be deleted!"
        return render(request, 'users/delete.html', {'warning_message': warning_message})

    if request.method == 'POST':
        user = MyUser.objects.get(pk=request.user.pk)
        user.delete()
        return redirect("home:home")

users/templates/users/change.html
{% extends 'base.html' %}

{% block title %}|Account{% endblock %}
{% block sidebar %}{% include "users/sidebar.html" %}{% endblock %}
{% block body_title %}Change Data{% endblock %}

{% block body_content %}
    <form action="{% url 'users:change' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update</button>
    </form>
{% endblock %}

users/templates/users/create.html
{% extends 'users/login.html' %}

{% block content %}
    <div class="form-wrap">
        <h1>Register</h1>
        <p>It's free</p>
        <form action="{% url 'users:create' %}" method="post">
            {% csrf_token %}
            {% for field in registration_form %}
                <div class="form-group">
                    {{field.label_tag}}
                    {{ field }}
                </div>
                {% for error in field.errors %}
                    <p class="error">{{ error }}</p>
                {% endfor %}
            {% endfor %}
            <button type="submit">Sign Up</button>
            <p class="bottom-text">
                By clicking the Sign Up button, you agree to give your soul to developing better world.
            </p>
        </form>
    </div>
    <footer>
        <p>Already have an account? <a href="{% url 'users:login' %}">Login Here</a></p>
    </footer>
{% endblock %}

users/templates/users/delete.html
{% extends 'base.html' %}

{% block title %}|Account{% endblock %}
{% block sidebar %}{% include "users/sidebar.html" %}{% endblock %}
{% block body_title %}Delete Account{% endblock %}

{% block body_content %}
    <div class="alert alert-danger" role="alert">{{ warning_message }}</div>
    <form action="{% url 'users:delete' %}" method="POST" class="text-center">
        {% csrf_token %}
        <button type="submit" class="btn btn-outline-danger">Delete</button>
    </form>
{% endblock %}

users/templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Zen Projects</title>
    <link rel="stylesheet" href="{% static 'users/css/sign_up_in.css' %}">
</head>
<body>
    <div id="container">
        {% block content %}
            <div class="form-wrap">
                <h1>Log in</h1>
                <form action="{% url 'users:login' %}" method="post">
                    {% csrf_token %}
                    {% for field in login_form %}
                        <div class="form-group">
                            {{ field.label_tag }}
                            {{ field }}
                        </div>
                        {% for error in field.errors %}
                            <p class="error">{{ error }}</p>
                        {% endfor %}
                    {% endfor %}
                    {% for error in login_form.non_field_errors %}
                        <div class="error">{{ error }}</div>
                    {% endfor %}
                    <button type="submit">Log in</button>
                </form>
            </div>
            <footer>
                <p>Dont have a account? <a href="{% url 'users:create' %}">Register Here</a></p>
            </footer>
        {% endblock %}
    </div>
</body>
</html>

users/templates/users/sidebar.html
{% include "snippets/sidebar/account.html" %}
{% include "snippets/sidebar/projects.html" %}

users/templates/users/view_myself.html
{% extends 'base.html' %}
{% load static %}

{% block title %}|Account{% endblock %}
{% block stylesheet %}<link rel="stylesheet" href="{% static 'users/css/change_delete_button.css' %}">{% endblock %}
{% block sidebar %}{% include "users/sidebar.html" %}{% endblock %}
{% block body_title %}My Account{% endblock %}

{% block body_content %}
    <div class="table_wrapper">
        <div class="table_line columns-3">
            <div class="line_item">Username</div>
            <div class="line_item">Email</div>
            <div class="line_item">Date joined</div>
        </div>
        <div class="table_line columns-3">
            <div class="line_item">{{ request.user.username }}</div>
            <div class="line_item">{{ request.user.email }}</div>
            <div class="line_item">{{ date_registered }}</div>
        </div>
    </div>
    <div class="center">
        <div class="inline-block">
        <div class="options-wrapper">
            <a class="option_1" href="{% url 'users:change' %}">CHANGE</a>
            <a class="option_2" href="{% url 'users:delete' %}">DELETE</a>
        </div>
    </div>
    </div>
{% endblock %}